version: '3'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    networks:
      - devopsnetwork
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: lahdid/devops:back
    restart: on-failure
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_DRIVERCLASSNAME: "com.mysql.cj.jdbc.Driver"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/devops?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
    depends_on:
      - mysql
    networks:
      - devopsnetwork

  # Angular service
  angular-app:
    image: lahdid/devops:front
    ports:
      - "4200:4200"
    depends_on:
      - springboot-app
    networks:
      - devopsnetwork

networks:
  devopsnetwork:

volumes:
  mysql-data:

